name: PA One command runner test
run-name: ${{ inputs.test_name }} on ${{ inputs.tag }} for build ${{ inputs.build_id }}

on:
  workflow_call:
    inputs:
      dataset_id:
        description: Attribution Dataset id
        required: true
        type: number
      input_path:
        description: S3 path to synthetic attribution data
        required: false
        default: https://fbpcs-github-e2e.s3.us-west-2.amazonaws.com/attribution/inputs/partner_e2e_input.csv
        type: string
      expected_result_path:
        description: S3 path to expected results from synthetic run
        required: false
        default: https://fbpcs-github-e2e.s3.us-west-2.amazonaws.com/attribution/results/partner_expected_result_last_click.json
        type: string
      build_id:
        description: The build id
        required: false
        default: 'test build'
        type: string
      test_name:
        description: The name of the type of tests that are being run
        required: false
        default: 'PA E2E Tests'
        type: string
      tag:
        description: Version tag to use
        required: false
        default: rc
        type: string
      tracker_hash:
        description: '[Internal usage] Used for tracking workflow job status within Meta infra'
        required: false
        type: string

  workflow_dispatch:
    inputs:
      dataset_id:
        description: Attribution Dataset id
        required: true
        default: '1127612294482487'
      input_path:
        description: S3 path to synthetic attribution data
        required: true
        default: https://fbpcs-github-e2e.s3.us-west-2.amazonaws.com/attribution/inputs/partner_e2e_input.csv
      expected_result_path:
        description: S3 path to expected results from synthetic run
        required: true
        default: https://fbpcs-github-e2e.s3.us-west-2.amazonaws.com/attribution/results/partner_expected_result_last_click.json
      build_id:
        description: The build id
        required: false
        default: 'test build'
      test_name:
        description: The name of the type of tests that are being run
        default: 'PA E2E Tests'
        type: 'choice'
        options:
          - PA E2E Tests
          - Multi-key PA E2E Tests
      tag:
        description: Version tag to use
        required: true
        default: rc
      tracker_hash:
        description: '[Internal usage] Used for tracking workflow job status within Meta infra'
        required: false
        type: string

env:
  FBPCS_CONTAINER_REPO_URL: ghcr.io/facebookresearch/fbpcs
  FBPCS_IMAGE_NAME: coordinator
  FBPCS_GRAPH_API_TOKEN: ${{ secrets.FBPCS_GRAPH_API_TOKEN }}

jobs:
  ### Private Attribution E2E tests

  pa_test:
    name: Private Attribution E2E Tests
    runs-on: [self-hosted, fbpcs-e2e-test-runner]
    timeout-minutes: 90
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Print Tracker Hash
        run: echo ${{ inputs.tracker_hash}}

      - name: One Command runner
        run: |
          ./fbpcs/scripts/run_fbpcs.sh run_attribution \
          --dataset_id=${{ inputs.dataset_id }} \
          --attribution_rule="last_click_1d" \
          --input_path=${{ inputs.input_path }} \
          --aggregation_type="measurement" \
          --concurrency=4 \
          --num_files_per_mpc_container=4 \
          --config=./fbpcs/tests/github/config_one_command_runner_test.yml \
          --timestamp="1646870400" \
          --k_anonymity_threshold=0 \
          -- \
          --version=${{ inputs.tag }}
      - name: Validate Results
        # instances are named after ent ids, so we are going to look for filenames that consist of only numbers and then run validation on them
        # the fbpcs_instances directory is where instances are written to (feature of run_fbpcs.sh)
        # the config.yml specifies that /fbpcs_instances is the instance repo, which is the source of the "/{}"
        run: |
          find fbpcs_instances -regex 'fbpcs_instances/[0-9]+' | xargs -I {} ./fbpcs/scripts/run_fbpcs.sh \
          validate \
          "/{}" \
          --config=./fbpcs/tests/github/config_one_command_runner_test.yml \
          --expected_result_path=${{ inputs.expected_result_path }} \
          -- \
          --version=${{ inputs.tag }}
